---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5.0-jdk-8

inputs:
  - name: zebedee

outputs:
  - name: build

params:
  APPLICATION:

run:
  path: zebedee/ci/scripts/build.sh
